<?xml version="1.0" encoding="utf-8"?><Database Name="Messages" Class="MessagesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=GT683\SQL2012EXP;Initial Catalog=Messages;Integrated Security=True" SettingsObjectName="DataHelper.Properties.Settings" SettingsPropertyName="HOME" Provider="System.Data.SqlClient" />
  <Table Name="dbo.RelativeEmployee" Member="RelativeEmployees">
    <Type Name="RelativeEmployee">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RelativeEmpNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UnconfirmedUsers" Member="UnconfirmedUsers">
    <Type Name="UnconfirmedUser">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DateRegistered" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmationCode" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShareCapital" Member="ShareCapitals">
    <Type Name="ShareCapital">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShareCapital" Member="ShareCapital1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="College" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Dept" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="DateConfirmed" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MemberStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateHired" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ATMAccountNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TINNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SSSNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CivilStatus" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FatherOccupation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MotherName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MotherOccupation" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LegalSpouse" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SpouseEmployer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusinessName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BusinessAddress" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OtherSourceOfIncome" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EmergencyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmergencyNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RegDump" Member="RegDumps">
    <Type Name="RegDump">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Data" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AccessTokens" Member="AccessTokens">
    <Type Name="AccessToken">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccessToken" Member="AccessToken1" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShareCapitalPayments" Member="ShareCapitalPayments">
    <Type Name="ShareCapitalPayment">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DatePaid" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoanTypes" Member="LoanTypes">
    <Type Name="LoanType">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoanType" Member="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoanAmountMatrix" Member="LoanAmountMatrixes">
    <Type Name="LoanAmountMatrix">
      <Column Name="RecordID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoanType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoanAmount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RequiredShareCapital" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Interest" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MonthsPayable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProcessingFee" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnconfirmedLoan" Member="UnconfirmedLoans">
    <Type Name="UnconfirmedLoan">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ConfirmedByMaker" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ConfirmedByCoMaker" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateFiled" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ConfirmCodeMakerSMS" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="ConfirmCodeCoMakerSMS" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="ConfirmCodeMakerEmail" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="ConfirmCodeCoMakerEmail" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
      <Column Name="ConfirmedByCoMaker2" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ConfirmCodeCoMaker2SMS" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="ConfirmCodeCoMaker2Email" Type="System.String" DbType="NVarChar(35)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoanApplication" Member="LoanApplications">
    <Type Name="LoanApplication">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmpNo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CoMakerEmpNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TypeOfLoan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="NoOfMonths" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Confirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DateApproved" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DateDue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CoMaker2EmpNo" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Done" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Declined" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>