#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHelper
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db2c447530bbbf4501bfd9a466008d7240")]
	public partial class MessagesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccessToken(AccessToken instance);
    partial void UpdateAccessToken(AccessToken instance);
    partial void DeleteAccessToken(AccessToken instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertInboundSM(InboundSM instance);
    partial void UpdateInboundSM(InboundSM instance);
    partial void DeleteInboundSM(InboundSM instance);
    partial void InsertLoanAmountMatrix(LoanAmountMatrix instance);
    partial void UpdateLoanAmountMatrix(LoanAmountMatrix instance);
    partial void DeleteLoanAmountMatrix(LoanAmountMatrix instance);
    partial void InsertLoanApplication(LoanApplication instance);
    partial void UpdateLoanApplication(LoanApplication instance);
    partial void DeleteLoanApplication(LoanApplication instance);
    partial void InsertLoanType(LoanType instance);
    partial void UpdateLoanType(LoanType instance);
    partial void DeleteLoanType(LoanType instance);
    partial void InsertPayment(Payment instance);
    partial void UpdatePayment(Payment instance);
    partial void DeletePayment(Payment instance);
    partial void InsertRegDump(RegDump instance);
    partial void UpdateRegDump(RegDump instance);
    partial void DeleteRegDump(RegDump instance);
    partial void InsertRelativeEmployee(RelativeEmployee instance);
    partial void UpdateRelativeEmployee(RelativeEmployee instance);
    partial void DeleteRelativeEmployee(RelativeEmployee instance);
    partial void InsertShareCapital(ShareCapital instance);
    partial void UpdateShareCapital(ShareCapital instance);
    partial void DeleteShareCapital(ShareCapital instance);
    partial void InsertShareCapitalPayment(ShareCapitalPayment instance);
    partial void UpdateShareCapitalPayment(ShareCapitalPayment instance);
    partial void DeleteShareCapitalPayment(ShareCapitalPayment instance);
    partial void InsertUnconfirmedUser(UnconfirmedUser instance);
    partial void UpdateUnconfirmedUser(UnconfirmedUser instance);
    partial void DeleteUnconfirmedUser(UnconfirmedUser instance);
    partial void InsertUserBeneficiary(UserBeneficiary instance);
    partial void UpdateUserBeneficiary(UserBeneficiary instance);
    partial void DeleteUserBeneficiary(UserBeneficiary instance);
    #endregion
		
		public MessagesDataContext() : 
				base(global::DataHelper.Properties.Settings.Default.PROD, mappingSource)
		{
			OnCreated();
		}
		
		public MessagesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MessagesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MessagesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MessagesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AccessToken> AccessTokens
		{
			get
			{
				return this.GetTable<AccessToken>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<AdminAccount> AdminAccounts
		{
			get
			{
				return this.GetTable<AdminAccount>();
			}
		}
		
		public System.Data.Linq.Table<College> Colleges
		{
			get
			{
				return this.GetTable<College>();
			}
		}
		
		public System.Data.Linq.Table<Department> Departments
		{
			get
			{
				return this.GetTable<Department>();
			}
		}
		
		public System.Data.Linq.Table<InboundSM> InboundSMs
		{
			get
			{
				return this.GetTable<InboundSM>();
			}
		}
		
		public System.Data.Linq.Table<LoanAmountMatrix> LoanAmountMatrixes
		{
			get
			{
				return this.GetTable<LoanAmountMatrix>();
			}
		}
		
		public System.Data.Linq.Table<LoanApplication> LoanApplications
		{
			get
			{
				return this.GetTable<LoanApplication>();
			}
		}
		
		public System.Data.Linq.Table<LoanType> LoanTypes
		{
			get
			{
				return this.GetTable<LoanType>();
			}
		}
		
		public System.Data.Linq.Table<MSG> MSGs
		{
			get
			{
				return this.GetTable<MSG>();
			}
		}
		
		public System.Data.Linq.Table<Payment> Payments
		{
			get
			{
				return this.GetTable<Payment>();
			}
		}
		
		public System.Data.Linq.Table<RegDump> RegDumps
		{
			get
			{
				return this.GetTable<RegDump>();
			}
		}
		
		public System.Data.Linq.Table<RelativeEmployee> RelativeEmployees
		{
			get
			{
				return this.GetTable<RelativeEmployee>();
			}
		}
		
		public System.Data.Linq.Table<ShareCapital> ShareCapitals
		{
			get
			{
				return this.GetTable<ShareCapital>();
			}
		}
		
		public System.Data.Linq.Table<ShareCapitalPayment> ShareCapitalPayments
		{
			get
			{
				return this.GetTable<ShareCapitalPayment>();
			}
		}
		
		public System.Data.Linq.Table<UnconfirmedLoan> UnconfirmedLoans
		{
			get
			{
				return this.GetTable<UnconfirmedLoan>();
			}
		}
		
		public System.Data.Linq.Table<UnconfirmedUser> UnconfirmedUsers
		{
			get
			{
				return this.GetTable<UnconfirmedUser>();
			}
		}
		
		public System.Data.Linq.Table<UserBeneficiary> UserBeneficiaries
		{
			get
			{
				return this.GetTable<UserBeneficiary>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AccessTokens")]
	public partial class AccessToken : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private string _AccessToken1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnAccessToken1Changing(string value);
    partial void OnAccessToken1Changed();
    #endregion
		
		public AccessToken()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="AccessToken", Storage="_AccessToken1", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string AccessToken1
		{
			get
			{
				return this._AccessToken1;
			}
			set
			{
				if ((this._AccessToken1 != value))
				{
					this.OnAccessToken1Changing(value);
					this.SendPropertyChanging();
					this._AccessToken1 = value;
					this.SendPropertyChanged("AccessToken1");
					this.OnAccessToken1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private string _UserType;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _MiddleName;
		
		private string _Email;
		
		private string _Password;
		
		private string _Address;
		
		private System.Nullable<System.DateTime> _Birthday;
		
		private string _College;
		
		private string _Dept;
		
		private string _PhoneNumber;
		
		private System.Nullable<System.DateTime> _DateConfirmed;
		
		private string _MemberStatus;
		
		private System.Nullable<System.DateTime> _DateHired;
		
		private string _Picture;
		
		private string _ATMAccountNo;
		
		private string _TINNo;
		
		private string _SSSNo;
		
		private string _Gender;
		
		private string _CivilStatus;
		
		private string _FatherName;
		
		private string _FatherOccupation;
		
		private string _MotherName;
		
		private string _MotherOccupation;
		
		private string _LegalSpouse;
		
		private string _SpouseEmployer;
		
		private string _BusinessName;
		
		private string _BusinessAddress;
		
		private string _OtherSourceOfIncome;
		
		private string _EmergencyName;
		
		private string _EmergencyAddress;
		
		private string _EmergencyNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnUserTypeChanging(string value);
    partial void OnUserTypeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnBirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthdayChanged();
    partial void OnCollegeChanging(string value);
    partial void OnCollegeChanged();
    partial void OnDeptChanging(string value);
    partial void OnDeptChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnDateConfirmedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateConfirmedChanged();
    partial void OnMemberStatusChanging(string value);
    partial void OnMemberStatusChanged();
    partial void OnDateHiredChanging(System.Nullable<System.DateTime> value);
    partial void OnDateHiredChanged();
    partial void OnPictureChanging(string value);
    partial void OnPictureChanged();
    partial void OnATMAccountNoChanging(string value);
    partial void OnATMAccountNoChanged();
    partial void OnTINNoChanging(string value);
    partial void OnTINNoChanged();
    partial void OnSSSNoChanging(string value);
    partial void OnSSSNoChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnCivilStatusChanging(string value);
    partial void OnCivilStatusChanged();
    partial void OnFatherNameChanging(string value);
    partial void OnFatherNameChanged();
    partial void OnFatherOccupationChanging(string value);
    partial void OnFatherOccupationChanged();
    partial void OnMotherNameChanging(string value);
    partial void OnMotherNameChanged();
    partial void OnMotherOccupationChanging(string value);
    partial void OnMotherOccupationChanged();
    partial void OnLegalSpouseChanging(string value);
    partial void OnLegalSpouseChanged();
    partial void OnSpouseEmployerChanging(string value);
    partial void OnSpouseEmployerChanged();
    partial void OnBusinessNameChanging(string value);
    partial void OnBusinessNameChanged();
    partial void OnBusinessAddressChanging(string value);
    partial void OnBusinessAddressChanged();
    partial void OnOtherSourceOfIncomeChanging(string value);
    partial void OnOtherSourceOfIncomeChanged();
    partial void OnEmergencyNameChanging(string value);
    partial void OnEmergencyNameChanged();
    partial void OnEmergencyAddressChanging(string value);
    partial void OnEmergencyAddressChanged();
    partial void OnEmergencyNumberChanging(string value);
    partial void OnEmergencyNumberChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this.OnUserTypeChanging(value);
					this.SendPropertyChanging();
					this._UserType = value;
					this.SendPropertyChanged("UserType");
					this.OnUserTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="NVarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(150)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="Date")]
		public System.Nullable<System.DateTime> Birthday
		{
			get
			{
				return this._Birthday;
			}
			set
			{
				if ((this._Birthday != value))
				{
					this.OnBirthdayChanging(value);
					this.SendPropertyChanging();
					this._Birthday = value;
					this.SendPropertyChanged("Birthday");
					this.OnBirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_College", DbType="NVarChar(30)")]
		public string College
		{
			get
			{
				return this._College;
			}
			set
			{
				if ((this._College != value))
				{
					this.OnCollegeChanging(value);
					this.SendPropertyChanging();
					this._College = value;
					this.SendPropertyChanged("College");
					this.OnCollegeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dept", DbType="NVarChar(30)")]
		public string Dept
		{
			get
			{
				return this._Dept;
			}
			set
			{
				if ((this._Dept != value))
				{
					this.OnDeptChanging(value);
					this.SendPropertyChanging();
					this._Dept = value;
					this.SendPropertyChanged("Dept");
					this.OnDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateConfirmed", DbType="Date")]
		public System.Nullable<System.DateTime> DateConfirmed
		{
			get
			{
				return this._DateConfirmed;
			}
			set
			{
				if ((this._DateConfirmed != value))
				{
					this.OnDateConfirmedChanging(value);
					this.SendPropertyChanging();
					this._DateConfirmed = value;
					this.SendPropertyChanged("DateConfirmed");
					this.OnDateConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberStatus", DbType="NVarChar(50)")]
		public string MemberStatus
		{
			get
			{
				return this._MemberStatus;
			}
			set
			{
				if ((this._MemberStatus != value))
				{
					this.OnMemberStatusChanging(value);
					this.SendPropertyChanging();
					this._MemberStatus = value;
					this.SendPropertyChanged("MemberStatus");
					this.OnMemberStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateHired", DbType="Date")]
		public System.Nullable<System.DateTime> DateHired
		{
			get
			{
				return this._DateHired;
			}
			set
			{
				if ((this._DateHired != value))
				{
					this.OnDateHiredChanging(value);
					this.SendPropertyChanging();
					this._DateHired = value;
					this.SendPropertyChanged("DateHired");
					this.OnDateHiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(MAX)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATMAccountNo", DbType="NVarChar(50)")]
		public string ATMAccountNo
		{
			get
			{
				return this._ATMAccountNo;
			}
			set
			{
				if ((this._ATMAccountNo != value))
				{
					this.OnATMAccountNoChanging(value);
					this.SendPropertyChanging();
					this._ATMAccountNo = value;
					this.SendPropertyChanged("ATMAccountNo");
					this.OnATMAccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINNo", DbType="NVarChar(50)")]
		public string TINNo
		{
			get
			{
				return this._TINNo;
			}
			set
			{
				if ((this._TINNo != value))
				{
					this.OnTINNoChanging(value);
					this.SendPropertyChanging();
					this._TINNo = value;
					this.SendPropertyChanged("TINNo");
					this.OnTINNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSSNo", DbType="NVarChar(50)")]
		public string SSSNo
		{
			get
			{
				return this._SSSNo;
			}
			set
			{
				if ((this._SSSNo != value))
				{
					this.OnSSSNoChanging(value);
					this.SendPropertyChanging();
					this._SSSNo = value;
					this.SendPropertyChanged("SSSNo");
					this.OnSSSNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CivilStatus", DbType="NVarChar(20)")]
		public string CivilStatus
		{
			get
			{
				return this._CivilStatus;
			}
			set
			{
				if ((this._CivilStatus != value))
				{
					this.OnCivilStatusChanging(value);
					this.SendPropertyChanging();
					this._CivilStatus = value;
					this.SendPropertyChanged("CivilStatus");
					this.OnCivilStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherName", DbType="NVarChar(50)")]
		public string FatherName
		{
			get
			{
				return this._FatherName;
			}
			set
			{
				if ((this._FatherName != value))
				{
					this.OnFatherNameChanging(value);
					this.SendPropertyChanging();
					this._FatherName = value;
					this.SendPropertyChanged("FatherName");
					this.OnFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherOccupation", DbType="NVarChar(50)")]
		public string FatherOccupation
		{
			get
			{
				return this._FatherOccupation;
			}
			set
			{
				if ((this._FatherOccupation != value))
				{
					this.OnFatherOccupationChanging(value);
					this.SendPropertyChanging();
					this._FatherOccupation = value;
					this.SendPropertyChanged("FatherOccupation");
					this.OnFatherOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(50)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this.OnMotherNameChanging(value);
					this.SendPropertyChanging();
					this._MotherName = value;
					this.SendPropertyChanged("MotherName");
					this.OnMotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherOccupation", DbType="NVarChar(50)")]
		public string MotherOccupation
		{
			get
			{
				return this._MotherOccupation;
			}
			set
			{
				if ((this._MotherOccupation != value))
				{
					this.OnMotherOccupationChanging(value);
					this.SendPropertyChanging();
					this._MotherOccupation = value;
					this.SendPropertyChanged("MotherOccupation");
					this.OnMotherOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegalSpouse", DbType="NVarChar(50)")]
		public string LegalSpouse
		{
			get
			{
				return this._LegalSpouse;
			}
			set
			{
				if ((this._LegalSpouse != value))
				{
					this.OnLegalSpouseChanging(value);
					this.SendPropertyChanging();
					this._LegalSpouse = value;
					this.SendPropertyChanged("LegalSpouse");
					this.OnLegalSpouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseEmployer", DbType="NVarChar(50)")]
		public string SpouseEmployer
		{
			get
			{
				return this._SpouseEmployer;
			}
			set
			{
				if ((this._SpouseEmployer != value))
				{
					this.OnSpouseEmployerChanging(value);
					this.SendPropertyChanging();
					this._SpouseEmployer = value;
					this.SendPropertyChanged("SpouseEmployer");
					this.OnSpouseEmployerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessName", DbType="NVarChar(50)")]
		public string BusinessName
		{
			get
			{
				return this._BusinessName;
			}
			set
			{
				if ((this._BusinessName != value))
				{
					this.OnBusinessNameChanging(value);
					this.SendPropertyChanging();
					this._BusinessName = value;
					this.SendPropertyChanged("BusinessName");
					this.OnBusinessNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BusinessAddress", DbType="NVarChar(150)")]
		public string BusinessAddress
		{
			get
			{
				return this._BusinessAddress;
			}
			set
			{
				if ((this._BusinessAddress != value))
				{
					this.OnBusinessAddressChanging(value);
					this.SendPropertyChanging();
					this._BusinessAddress = value;
					this.SendPropertyChanged("BusinessAddress");
					this.OnBusinessAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherSourceOfIncome", DbType="NVarChar(250)")]
		public string OtherSourceOfIncome
		{
			get
			{
				return this._OtherSourceOfIncome;
			}
			set
			{
				if ((this._OtherSourceOfIncome != value))
				{
					this.OnOtherSourceOfIncomeChanging(value);
					this.SendPropertyChanging();
					this._OtherSourceOfIncome = value;
					this.SendPropertyChanged("OtherSourceOfIncome");
					this.OnOtherSourceOfIncomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyName", DbType="NVarChar(50)")]
		public string EmergencyName
		{
			get
			{
				return this._EmergencyName;
			}
			set
			{
				if ((this._EmergencyName != value))
				{
					this.OnEmergencyNameChanging(value);
					this.SendPropertyChanging();
					this._EmergencyName = value;
					this.SendPropertyChanged("EmergencyName");
					this.OnEmergencyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyAddress", DbType="NVarChar(50)")]
		public string EmergencyAddress
		{
			get
			{
				return this._EmergencyAddress;
			}
			set
			{
				if ((this._EmergencyAddress != value))
				{
					this.OnEmergencyAddressChanging(value);
					this.SendPropertyChanging();
					this._EmergencyAddress = value;
					this.SendPropertyChanged("EmergencyAddress");
					this.OnEmergencyAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmergencyNumber", DbType="NVarChar(50)")]
		public string EmergencyNumber
		{
			get
			{
				return this._EmergencyNumber;
			}
			set
			{
				if ((this._EmergencyNumber != value))
				{
					this.OnEmergencyNumberChanging(value);
					this.SendPropertyChanging();
					this._EmergencyNumber = value;
					this.SendPropertyChanged("EmergencyNumber");
					this.OnEmergencyNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminAccount")]
	public partial class AdminAccount
	{
		
		private string _Username;
		
		private string _Password;
		
		public AdminAccount()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.College")]
	public partial class College
	{
		
		private int _CollegeID;
		
		private string _CollegeName;
		
		public College()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int CollegeID
		{
			get
			{
				return this._CollegeID;
			}
			set
			{
				if ((this._CollegeID != value))
				{
					this._CollegeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeName", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string CollegeName
		{
			get
			{
				return this._CollegeName;
			}
			set
			{
				if ((this._CollegeName != value))
				{
					this._CollegeName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department")]
	public partial class Department
	{
		
		private int _CollegeID;
		
		private int _DepartmentID;
		
		private string _DepartmentName;
		
		public Department()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollegeID", DbType="Int NOT NULL")]
		public int CollegeID
		{
			get
			{
				return this._CollegeID;
			}
			set
			{
				if ((this._CollegeID != value))
				{
					this._CollegeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int NOT NULL")]
		public int DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this._DepartmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DepartmentName
		{
			get
			{
				return this._DepartmentName;
			}
			set
			{
				if ((this._DepartmentName != value))
				{
					this._DepartmentName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InboundSMS")]
	public partial class InboundSM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private System.Nullable<System.DateTime> _MsgDateTime;
		
		private string _DestinationAddress;
		
		private string _MessageId;
		
		private string _Message;
		
		private string _ResourceURL;
		
		private string _SenderAddress;
		
		private System.Nullable<System.DateTime> _Timestamp;
		
		private System.Nullable<bool> _IsRead;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnMsgDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnMsgDateTimeChanged();
    partial void OnDestinationAddressChanging(string value);
    partial void OnDestinationAddressChanged();
    partial void OnMessageIdChanging(string value);
    partial void OnMessageIdChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnResourceURLChanging(string value);
    partial void OnResourceURLChanged();
    partial void OnSenderAddressChanging(string value);
    partial void OnSenderAddressChanged();
    partial void OnTimestampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimestampChanged();
    partial void OnIsReadChanging(System.Nullable<bool> value);
    partial void OnIsReadChanged();
    #endregion
		
		public InboundSM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MsgDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> MsgDateTime
		{
			get
			{
				return this._MsgDateTime;
			}
			set
			{
				if ((this._MsgDateTime != value))
				{
					this.OnMsgDateTimeChanging(value);
					this.SendPropertyChanging();
					this._MsgDateTime = value;
					this.SendPropertyChanged("MsgDateTime");
					this.OnMsgDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationAddress", DbType="NVarChar(255)")]
		public string DestinationAddress
		{
			get
			{
				return this._DestinationAddress;
			}
			set
			{
				if ((this._DestinationAddress != value))
				{
					this.OnDestinationAddressChanging(value);
					this.SendPropertyChanging();
					this._DestinationAddress = value;
					this.SendPropertyChanged("DestinationAddress");
					this.OnDestinationAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageId", DbType="NVarChar(255)")]
		public string MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if ((this._MessageId != value))
				{
					this.OnMessageIdChanging(value);
					this.SendPropertyChanging();
					this._MessageId = value;
					this.SendPropertyChanged("MessageId");
					this.OnMessageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(255)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceURL", DbType="NVarChar(255)")]
		public string ResourceURL
		{
			get
			{
				return this._ResourceURL;
			}
			set
			{
				if ((this._ResourceURL != value))
				{
					this.OnResourceURLChanging(value);
					this.SendPropertyChanging();
					this._ResourceURL = value;
					this.SendPropertyChanged("ResourceURL");
					this.OnResourceURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SenderAddress", DbType="NVarChar(50)")]
		public string SenderAddress
		{
			get
			{
				return this._SenderAddress;
			}
			set
			{
				if ((this._SenderAddress != value))
				{
					this.OnSenderAddressChanging(value);
					this.SendPropertyChanging();
					this._SenderAddress = value;
					this.SendPropertyChanged("SenderAddress");
					this.OnSenderAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timestamp", DbType="DateTime")]
		public System.Nullable<System.DateTime> Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				if ((this._Timestamp != value))
				{
					this.OnTimestampChanging(value);
					this.SendPropertyChanging();
					this._Timestamp = value;
					this.SendPropertyChanged("Timestamp");
					this.OnTimestampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRead", DbType="Bit")]
		public System.Nullable<bool> IsRead
		{
			get
			{
				return this._IsRead;
			}
			set
			{
				if ((this._IsRead != value))
				{
					this.OnIsReadChanging(value);
					this.SendPropertyChanging();
					this._IsRead = value;
					this.SendPropertyChanged("IsRead");
					this.OnIsReadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoanAmountMatrix")]
	public partial class LoanAmountMatrix : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private int _LoanType;
		
		private double _LoanAmount;
		
		private double _RequiredShareCapital;
		
		private double _Interest;
		
		private int _MonthsPayable;
		
		private System.Nullable<double> _ProcessingFee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnLoanTypeChanging(int value);
    partial void OnLoanTypeChanged();
    partial void OnLoanAmountChanging(double value);
    partial void OnLoanAmountChanged();
    partial void OnRequiredShareCapitalChanging(double value);
    partial void OnRequiredShareCapitalChanged();
    partial void OnInterestChanging(double value);
    partial void OnInterestChanged();
    partial void OnMonthsPayableChanging(int value);
    partial void OnMonthsPayableChanged();
    partial void OnProcessingFeeChanging(System.Nullable<double> value);
    partial void OnProcessingFeeChanged();
    #endregion
		
		public LoanAmountMatrix()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoanType", DbType="Int NOT NULL")]
		public int LoanType
		{
			get
			{
				return this._LoanType;
			}
			set
			{
				if ((this._LoanType != value))
				{
					this.OnLoanTypeChanging(value);
					this.SendPropertyChanging();
					this._LoanType = value;
					this.SendPropertyChanged("LoanType");
					this.OnLoanTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoanAmount", DbType="Float NOT NULL")]
		public double LoanAmount
		{
			get
			{
				return this._LoanAmount;
			}
			set
			{
				if ((this._LoanAmount != value))
				{
					this.OnLoanAmountChanging(value);
					this.SendPropertyChanging();
					this._LoanAmount = value;
					this.SendPropertyChanged("LoanAmount");
					this.OnLoanAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequiredShareCapital", DbType="Float NOT NULL")]
		public double RequiredShareCapital
		{
			get
			{
				return this._RequiredShareCapital;
			}
			set
			{
				if ((this._RequiredShareCapital != value))
				{
					this.OnRequiredShareCapitalChanging(value);
					this.SendPropertyChanging();
					this._RequiredShareCapital = value;
					this.SendPropertyChanged("RequiredShareCapital");
					this.OnRequiredShareCapitalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interest", DbType="Float NOT NULL")]
		public double Interest
		{
			get
			{
				return this._Interest;
			}
			set
			{
				if ((this._Interest != value))
				{
					this.OnInterestChanging(value);
					this.SendPropertyChanging();
					this._Interest = value;
					this.SendPropertyChanged("Interest");
					this.OnInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthsPayable", DbType="Int NOT NULL")]
		public int MonthsPayable
		{
			get
			{
				return this._MonthsPayable;
			}
			set
			{
				if ((this._MonthsPayable != value))
				{
					this.OnMonthsPayableChanging(value);
					this.SendPropertyChanging();
					this._MonthsPayable = value;
					this.SendPropertyChanged("MonthsPayable");
					this.OnMonthsPayableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingFee", DbType="Float")]
		public System.Nullable<double> ProcessingFee
		{
			get
			{
				return this._ProcessingFee;
			}
			set
			{
				if ((this._ProcessingFee != value))
				{
					this.OnProcessingFeeChanging(value);
					this.SendPropertyChanging();
					this._ProcessingFee = value;
					this.SendPropertyChanged("ProcessingFee");
					this.OnProcessingFeeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoanApplication")]
	public partial class LoanApplication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TransactionID;
		
		private string _EmpNo;
		
		private string _CoMakerEmpNo;
		
		private string _TypeOfLoan;
		
		private string _Reason;
		
		private decimal _Amount;
		
		private int _NoOfMonths;
		
		private System.Nullable<bool> _Confirmed;
		
		private System.Nullable<System.DateTime> _DateApproved;
		
		private System.Nullable<System.DateTime> _DateDue;
		
		private string _CoMaker2EmpNo;
		
		private System.Nullable<bool> _Done;
		
		private System.Nullable<bool> _Declined;
		
		private System.Nullable<decimal> _Balance;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransactionIDChanging(int value);
    partial void OnTransactionIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnCoMakerEmpNoChanging(string value);
    partial void OnCoMakerEmpNoChanged();
    partial void OnTypeOfLoanChanging(string value);
    partial void OnTypeOfLoanChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnAmountChanging(decimal value);
    partial void OnAmountChanged();
    partial void OnNoOfMonthsChanging(int value);
    partial void OnNoOfMonthsChanged();
    partial void OnConfirmedChanging(System.Nullable<bool> value);
    partial void OnConfirmedChanged();
    partial void OnDateApprovedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateApprovedChanged();
    partial void OnDateDueChanging(System.Nullable<System.DateTime> value);
    partial void OnDateDueChanged();
    partial void OnCoMaker2EmpNoChanging(string value);
    partial void OnCoMaker2EmpNoChanged();
    partial void OnDoneChanging(System.Nullable<bool> value);
    partial void OnDoneChanged();
    partial void OnDeclinedChanging(System.Nullable<bool> value);
    partial void OnDeclinedChanged();
    partial void OnBalanceChanging(System.Nullable<decimal> value);
    partial void OnBalanceChanged();
    #endregion
		
		public LoanApplication()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoMakerEmpNo", DbType="NVarChar(10)")]
		public string CoMakerEmpNo
		{
			get
			{
				return this._CoMakerEmpNo;
			}
			set
			{
				if ((this._CoMakerEmpNo != value))
				{
					this.OnCoMakerEmpNoChanging(value);
					this.SendPropertyChanging();
					this._CoMakerEmpNo = value;
					this.SendPropertyChanged("CoMakerEmpNo");
					this.OnCoMakerEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfLoan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeOfLoan
		{
			get
			{
				return this._TypeOfLoan;
			}
			set
			{
				if ((this._TypeOfLoan != value))
				{
					this.OnTypeOfLoanChanging(value);
					this.SendPropertyChanging();
					this._TypeOfLoan = value;
					this.SendPropertyChanged("TypeOfLoan");
					this.OnTypeOfLoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this.OnReasonChanging(value);
					this.SendPropertyChanging();
					this._Reason = value;
					this.SendPropertyChanged("Reason");
					this.OnReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money NOT NULL")]
		public decimal Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfMonths", DbType="Int NOT NULL")]
		public int NoOfMonths
		{
			get
			{
				return this._NoOfMonths;
			}
			set
			{
				if ((this._NoOfMonths != value))
				{
					this.OnNoOfMonthsChanging(value);
					this.SendPropertyChanging();
					this._NoOfMonths = value;
					this.SendPropertyChanged("NoOfMonths");
					this.OnNoOfMonthsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmed", DbType="Bit")]
		public System.Nullable<bool> Confirmed
		{
			get
			{
				return this._Confirmed;
			}
			set
			{
				if ((this._Confirmed != value))
				{
					this.OnConfirmedChanging(value);
					this.SendPropertyChanging();
					this._Confirmed = value;
					this.SendPropertyChanged("Confirmed");
					this.OnConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateApproved", DbType="Date")]
		public System.Nullable<System.DateTime> DateApproved
		{
			get
			{
				return this._DateApproved;
			}
			set
			{
				if ((this._DateApproved != value))
				{
					this.OnDateApprovedChanging(value);
					this.SendPropertyChanging();
					this._DateApproved = value;
					this.SendPropertyChanged("DateApproved");
					this.OnDateApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDue", DbType="Date")]
		public System.Nullable<System.DateTime> DateDue
		{
			get
			{
				return this._DateDue;
			}
			set
			{
				if ((this._DateDue != value))
				{
					this.OnDateDueChanging(value);
					this.SendPropertyChanging();
					this._DateDue = value;
					this.SendPropertyChanged("DateDue");
					this.OnDateDueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoMaker2EmpNo", DbType="NVarChar(10)")]
		public string CoMaker2EmpNo
		{
			get
			{
				return this._CoMaker2EmpNo;
			}
			set
			{
				if ((this._CoMaker2EmpNo != value))
				{
					this.OnCoMaker2EmpNoChanging(value);
					this.SendPropertyChanging();
					this._CoMaker2EmpNo = value;
					this.SendPropertyChanged("CoMaker2EmpNo");
					this.OnCoMaker2EmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Done", DbType="Bit")]
		public System.Nullable<bool> Done
		{
			get
			{
				return this._Done;
			}
			set
			{
				if ((this._Done != value))
				{
					this.OnDoneChanging(value);
					this.SendPropertyChanging();
					this._Done = value;
					this.SendPropertyChanged("Done");
					this.OnDoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Declined", DbType="Bit")]
		public System.Nullable<bool> Declined
		{
			get
			{
				return this._Declined;
			}
			set
			{
				if ((this._Declined != value))
				{
					this.OnDeclinedChanging(value);
					this.SendPropertyChanging();
					this._Declined = value;
					this.SendPropertyChanged("Declined");
					this.OnDeclinedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoanTypes")]
	public partial class LoanType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _LoanType1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnLoanType1Changing(string value);
    partial void OnLoanType1Changed();
    #endregion
		
		public LoanType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LoanType", Storage="_LoanType1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoanType1
		{
			get
			{
				return this._LoanType1;
			}
			set
			{
				if ((this._LoanType1 != value))
				{
					this.OnLoanType1Changing(value);
					this.SendPropertyChanging();
					this._LoanType1 = value;
					this.SendPropertyChanged("LoanType1");
					this.OnLoanType1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MSGS")]
	public partial class MSG
	{
		
		private string _ID;
		
		private string _Source;
		
		private string _Msg1;
		
		private string _UDH;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		public MSG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(50)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this._Source = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Msg", Storage="_Msg1", DbType="NVarChar(MAX)")]
		public string Msg1
		{
			get
			{
				return this._Msg1;
			}
			set
			{
				if ((this._Msg1 != value))
				{
					this._Msg1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UDH", DbType="NVarChar(50)")]
		public string UDH
		{
			get
			{
				return this._UDH;
			}
			set
			{
				if ((this._UDH != value))
				{
					this._UDH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this._DateReceived = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payments")]
	public partial class Payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private int _TransactionID;
		
		private double _PayAmount;
		
		private string _Note;
		
		private System.Nullable<System.DateTime> _PayDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnTransactionIDChanging(int value);
    partial void OnTransactionIDChanged();
    partial void OnPayAmountChanging(double value);
    partial void OnPayAmountChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnPayDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPayDateChanged();
    #endregion
		
		public Payment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="Int NOT NULL")]
		public int TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayAmount", DbType="Float NOT NULL")]
		public double PayAmount
		{
			get
			{
				return this._PayAmount;
			}
			set
			{
				if ((this._PayAmount != value))
				{
					this.OnPayAmountChanging(value);
					this.SendPropertyChanging();
					this._PayAmount = value;
					this.SendPropertyChanged("PayAmount");
					this.OnPayAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(500)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PayDate
		{
			get
			{
				return this._PayDate;
			}
			set
			{
				if ((this._PayDate != value))
				{
					this.OnPayDateChanging(value);
					this.SendPropertyChanging();
					this._PayDate = value;
					this.SendPropertyChanged("PayDate");
					this.OnPayDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RegDump")]
	public partial class RegDump : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _Data;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    #endregion
		
		public RegDump()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RelativeEmployee")]
	public partial class RelativeEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private string _RelativeEmpNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnRelativeEmpNoChanging(string value);
    partial void OnRelativeEmpNoChanged();
    #endregion
		
		public RelativeEmployee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelativeEmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RelativeEmpNo
		{
			get
			{
				return this._RelativeEmpNo;
			}
			set
			{
				if ((this._RelativeEmpNo != value))
				{
					this.OnRelativeEmpNoChanging(value);
					this.SendPropertyChanging();
					this._RelativeEmpNo = value;
					this.SendPropertyChanged("RelativeEmpNo");
					this.OnRelativeEmpNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShareCapital")]
	public partial class ShareCapital : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private double _ShareCapital1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnShareCapital1Changing(double value);
    partial void OnShareCapital1Changed();
    #endregion
		
		public ShareCapital()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ShareCapital", Storage="_ShareCapital1", DbType="Float NOT NULL")]
		public double ShareCapital1
		{
			get
			{
				return this._ShareCapital1;
			}
			set
			{
				if ((this._ShareCapital1 != value))
				{
					this.OnShareCapital1Changing(value);
					this.SendPropertyChanging();
					this._ShareCapital1 = value;
					this.SendPropertyChanged("ShareCapital1");
					this.OnShareCapital1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShareCapitalPayments")]
	public partial class ShareCapitalPayment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private System.DateTime _DatePaid;
		
		private double _Amount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnDatePaidChanging(System.DateTime value);
    partial void OnDatePaidChanged();
    partial void OnAmountChanging(double value);
    partial void OnAmountChanged();
    #endregion
		
		public ShareCapitalPayment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePaid", DbType="DateTime NOT NULL")]
		public System.DateTime DatePaid
		{
			get
			{
				return this._DatePaid;
			}
			set
			{
				if ((this._DatePaid != value))
				{
					this.OnDatePaidChanging(value);
					this.SendPropertyChanging();
					this._DatePaid = value;
					this.SendPropertyChanged("DatePaid");
					this.OnDatePaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Float NOT NULL")]
		public double Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnconfirmedLoan")]
	public partial class UnconfirmedLoan
	{
		
		private int _TransactionID;
		
		private System.Nullable<bool> _ConfirmedByMaker;
		
		private System.Nullable<bool> _ConfirmedByCoMaker;
		
		private System.DateTime _DateFiled;
		
		private string _ConfirmCodeMakerSMS;
		
		private string _ConfirmCodeCoMakerSMS;
		
		private string _ConfirmCodeMakerEmail;
		
		private string _ConfirmCodeCoMakerEmail;
		
		private System.Nullable<bool> _ConfirmedByCoMaker2;
		
		private string _ConfirmCodeCoMaker2SMS;
		
		private string _ConfirmCodeCoMaker2Email;
		
		public UnconfirmedLoan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="Int NOT NULL")]
		public int TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this._TransactionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmedByMaker", DbType="Bit")]
		public System.Nullable<bool> ConfirmedByMaker
		{
			get
			{
				return this._ConfirmedByMaker;
			}
			set
			{
				if ((this._ConfirmedByMaker != value))
				{
					this._ConfirmedByMaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmedByCoMaker", DbType="Bit")]
		public System.Nullable<bool> ConfirmedByCoMaker
		{
			get
			{
				return this._ConfirmedByCoMaker;
			}
			set
			{
				if ((this._ConfirmedByCoMaker != value))
				{
					this._ConfirmedByCoMaker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFiled", DbType="Date NOT NULL")]
		public System.DateTime DateFiled
		{
			get
			{
				return this._DateFiled;
			}
			set
			{
				if ((this._DateFiled != value))
				{
					this._DateFiled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmCodeMakerSMS", DbType="NVarChar(6)")]
		public string ConfirmCodeMakerSMS
		{
			get
			{
				return this._ConfirmCodeMakerSMS;
			}
			set
			{
				if ((this._ConfirmCodeMakerSMS != value))
				{
					this._ConfirmCodeMakerSMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmCodeCoMakerSMS", DbType="NVarChar(6)")]
		public string ConfirmCodeCoMakerSMS
		{
			get
			{
				return this._ConfirmCodeCoMakerSMS;
			}
			set
			{
				if ((this._ConfirmCodeCoMakerSMS != value))
				{
					this._ConfirmCodeCoMakerSMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmCodeMakerEmail", DbType="NVarChar(35)")]
		public string ConfirmCodeMakerEmail
		{
			get
			{
				return this._ConfirmCodeMakerEmail;
			}
			set
			{
				if ((this._ConfirmCodeMakerEmail != value))
				{
					this._ConfirmCodeMakerEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmCodeCoMakerEmail", DbType="NVarChar(35)")]
		public string ConfirmCodeCoMakerEmail
		{
			get
			{
				return this._ConfirmCodeCoMakerEmail;
			}
			set
			{
				if ((this._ConfirmCodeCoMakerEmail != value))
				{
					this._ConfirmCodeCoMakerEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmedByCoMaker2", DbType="Bit")]
		public System.Nullable<bool> ConfirmedByCoMaker2
		{
			get
			{
				return this._ConfirmedByCoMaker2;
			}
			set
			{
				if ((this._ConfirmedByCoMaker2 != value))
				{
					this._ConfirmedByCoMaker2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmCodeCoMaker2SMS", DbType="NVarChar(6)")]
		public string ConfirmCodeCoMaker2SMS
		{
			get
			{
				return this._ConfirmCodeCoMaker2SMS;
			}
			set
			{
				if ((this._ConfirmCodeCoMaker2SMS != value))
				{
					this._ConfirmCodeCoMaker2SMS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmCodeCoMaker2Email", DbType="NVarChar(35)")]
		public string ConfirmCodeCoMaker2Email
		{
			get
			{
				return this._ConfirmCodeCoMaker2Email;
			}
			set
			{
				if ((this._ConfirmCodeCoMaker2Email != value))
				{
					this._ConfirmCodeCoMaker2Email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UnconfirmedUsers")]
	public partial class UnconfirmedUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private System.DateTime _DateRegistered;
		
		private string _ConfirmationCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnDateRegisteredChanging(System.DateTime value);
    partial void OnDateRegisteredChanged();
    partial void OnConfirmationCodeChanging(string value);
    partial void OnConfirmationCodeChanged();
    #endregion
		
		public UnconfirmedUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRegistered", DbType="Date NOT NULL")]
		public System.DateTime DateRegistered
		{
			get
			{
				return this._DateRegistered;
			}
			set
			{
				if ((this._DateRegistered != value))
				{
					this.OnDateRegisteredChanging(value);
					this.SendPropertyChanging();
					this._DateRegistered = value;
					this.SendPropertyChanged("DateRegistered");
					this.OnDateRegisteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConfirmationCode", DbType="NVarChar(35)")]
		public string ConfirmationCode
		{
			get
			{
				return this._ConfirmationCode;
			}
			set
			{
				if ((this._ConfirmationCode != value))
				{
					this.OnConfirmationCodeChanging(value);
					this.SendPropertyChanging();
					this._ConfirmationCode = value;
					this.SendPropertyChanged("ConfirmationCode");
					this.OnConfirmationCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserBeneficiaries")]
	public partial class UserBeneficiary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RecordID;
		
		private string _EmpNo;
		
		private string _BeneficiaryName;
		
		private System.DateTime _DOB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRecordIDChanging(int value);
    partial void OnRecordIDChanged();
    partial void OnEmpNoChanging(string value);
    partial void OnEmpNoChanged();
    partial void OnBeneficiaryNameChanging(string value);
    partial void OnBeneficiaryNameChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    #endregion
		
		public UserBeneficiary()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this.OnRecordIDChanging(value);
					this.SendPropertyChanging();
					this._RecordID = value;
					this.SendPropertyChanged("RecordID");
					this.OnRecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpNo", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string EmpNo
		{
			get
			{
				return this._EmpNo;
			}
			set
			{
				if ((this._EmpNo != value))
				{
					this.OnEmpNoChanging(value);
					this.SendPropertyChanging();
					this._EmpNo = value;
					this.SendPropertyChanged("EmpNo");
					this.OnEmpNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeneficiaryName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BeneficiaryName
		{
			get
			{
				return this._BeneficiaryName;
			}
			set
			{
				if ((this._BeneficiaryName != value))
				{
					this.OnBeneficiaryNameChanging(value);
					this.SendPropertyChanging();
					this._BeneficiaryName = value;
					this.SendPropertyChanged("BeneficiaryName");
					this.OnBeneficiaryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
